spring:
  data:
    mongodb:
      host: 192.168.83.128
      port: 27017
      authentication-database: admin
      username: mongoadmin
      password: D3v310p34202X-GD
      database: userdb
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
server:
  port: 9060
springdoc:
  packages-to-scan: 'link.grooverdev.web.api.demo.controller'
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %p %c{1.} [%t] %m%n"
  level:
    org.springframework.web: ERROR
    link.grooverdev.web.api: DEBUG
    org.hibernate: ERROR
  file:
    name: gd-app-user.log