spring:
  data:
    mongodb:
      database: userdb
      uri: mongodb+srv://groveralbino:Gr00v34D3v202X-GD@cluster0.b6lcpya.mongodb.net
server:
  port: 9060
springdoc:
  packages-to-scan: 'link.grooverdev.web.api.demo.controller'
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %p %c{1.} [%t] %m%n"
  level:
    org.springframework.web: ERROR
    link.grooverdev.web.api: DEBUG
    org.hibernate: ERROR
  file:
    name: gd-app-user.log
